const kessyData = {
  categories: [
    {
      title: "Budget Tech Picks",
      description: "Power banks, earbuds, lighting, storage, and smart accessories with broad buyer appeal.",
      link: "./shop.html?filter=Budget%20Tech%20Picks",
    },
    {
      title: "Best Value Deals",
      description: "Practical gadgets and work tools that feel easiest to recommend for the price.",
      link: "./shop.html?filter=Best%20Value%20Deals",
    },
    {
      title: "Phones",
      description: "Affordable Android picks and mid-range phone options with strong local demand.",
      link: "./shop.html?filter=Phones",
    },
    {
      title: "Laptops",
      description: "Refurbished and value-focused laptop options for work, study, and creators.",
      link: "./shop.html?filter=Laptops",
    },
  ],
  featuredDeals: [
    "budget-power-bank",
    "phone-redmi-a",
    "laptop-hp-elitebook",
    "budget-earbuds",
    "trend-smartwatch",
  ],
  products: [
    {
      id: "budget-power-bank",
      section: "budget",
      category: "Accessories",
      imageLabel: "Power",
      title: "20,000mAh Fast Charge Power Bank",
      description: "Reliable backup power for commuters, students, and small business owners.",
      price: "NGN 22,500",
      affiliateUrl: "#replace-with-affiliate-link-budget-power-bank",
      badge: "Budget Tech Pick",
    },
    {
      id: "budget-earbuds",
      section: "budget",
      category: "Accessories",
      imageLabel: "Audio",
      title: "Bluetooth Earbuds with Noise Isolation",
      description: "Affordable wireless audio for calls, music, and short-form content watching.",
      price: "NGN 18,900",
      affiliateUrl: "#replace-with-affiliate-link-budget-earbuds",
      badge: "Affordable Audio",
    },
    {
      id: "budget-ring-light",
      section: "budget",
      category: "Accessories",
      imageLabel: "Light",
      title: "USB Ring Light with Phone Holder",
      description: "A low-cost lighting upgrade for creators, vendors, and live sellers.",
      price: "NGN 24,500",
      affiliateUrl: "#replace-with-affiliate-link-budget-ring-light",
      badge: "Creator Budget Pick",
    },
    {
      id: "budget-keyboard",
      section: "budget",
      category: "Typing",
      imageLabel: "Keys",
      title: "Portable Bluetooth Keyboard",
      description: "Useful for tablets, phones, and lightweight office work on the go.",
      price: "NGN 27,000",
      affiliateUrl: "#replace-with-affiliate-link-budget-keyboard",
      badge: "Under NGN 30k",
    },
    {
      id: "value-ssd",
      section: "value",
      category: "Accessories",
      imageLabel: "SSD",
      title: "Portable SSD 512GB",
      description: "Fast storage for video files, business backups, and everyday data transfer.",
      price: "NGN 47,000",
      affiliateUrl: "#replace-with-affiliate-link-value-ssd",
      badge: "Best Value Deal",
    },
    {
      id: "value-router",
      section: "value",
      category: "Accessories",
      imageLabel: "WiFi",
      title: "4G LTE MiFi Router",
      description: "A practical internet solution for remote work, classes, and travel.",
      price: "NGN 33,500",
      affiliateUrl: "#replace-with-affiliate-link-value-router",
      badge: "Connectivity Pick",
    },
    {
      id: "value-mouse",
      section: "value",
      category: "Accessories",
      imageLabel: "Mouse",
      title: "Rechargeable Wireless Mouse",
      description: "Simple quality-of-life upgrade for laptop users and office setups.",
      price: "NGN 12,500",
      affiliateUrl: "#replace-with-affiliate-link-value-mouse",
      badge: "Best Value Deal",
    },
    {
      id: "value-speaker",
      section: "value",
      category: "Audio",
      imageLabel: "Speaker",
      title: "Portable Bluetooth Speaker",
      description: "Compact sound system with broad appeal for indoor and outdoor use.",
      price: "NGN 29,800",
      affiliateUrl: "#replace-with-affiliate-link-value-speaker",
      badge: "Value Audio",
    },
    {
      id: "trend-smartwatch",
      section: "trending",
      category: "Trending Gadgets",
      imageLabel: "Watch",
      title: "Fitness Smartwatch",
      description: "A trending gadget category for lifestyle, wellness, and gift-focused buyers.",
      price: "NGN 34,000",
      affiliateUrl: "#replace-with-affiliate-link-trending-smartwatch",
      badge: "Trending Product",
    },
    {
      id: "trend-game-pad",
      section: "trending",
      category: "Gaming",
      imageLabel: "Game",
      title: "Mobile Gaming Controller",
      description: "Popular among mobile gamers looking for a stronger play experience.",
      price: "NGN 31,500",
      affiliateUrl: "#replace-with-affiliate-link-trending-game-pad",
      badge: "Trending Product",
    },
    {
      id: "trend-laptop-stand",
      section: "trending",
      category: "Accessories",
      imageLabel: "Stand",
      title: "Adjustable Laptop Stand",
      description: "Clean desk accessory that fits work-from-home and student audiences.",
      price: "NGN 16,000",
      affiliateUrl: "#replace-with-affiliate-link-trending-laptop-stand",
      badge: "Trending Workspace",
    },
    {
      id: "trend-webcam",
      section: "trending",
      category: "Accessories",
      imageLabel: "Cam",
      title: "1080p USB Webcam",
      description: "Useful for meetings, online classes, livestreams, and basic creator setups.",
      price: "NGN 26,500",
      affiliateUrl: "#replace-with-affiliate-link-trending-webcam",
      badge: "Trending Product",
    },
    {
      id: "computer-laptop",
      section: "computers",
      category: "Laptops",
      imageLabel: "Laptop",
      title: "Refurbished Core i5 Laptop",
      description: "Popular entry-level computer option for work, browsing, and office tasks.",
      price: "NGN 245,000",
      affiliateUrl: "#replace-with-affiliate-link-computer-laptop",
      badge: "Computer Pick",
    },
    {
      id: "computer-mini-pc",
      section: "computers",
      category: "Laptops",
      imageLabel: "Mini PC",
      title: "Mini PC Office Bundle",
      description: "Compact setup for counters, small offices, and administrative work.",
      price: "NGN 189,000",
      affiliateUrl: "#replace-with-affiliate-link-computer-mini-pc",
      badge: "Computer Pick",
    },
    {
      id: "computer-monitor",
      section: "computers",
      category: "Accessories",
      imageLabel: "Screen",
      title: "22-inch Full HD Monitor",
      description: "Affordable display option for business, editing, and productivity desks.",
      price: "NGN 78,000",
      affiliateUrl: "#replace-with-affiliate-link-computer-monitor",
      badge: "Office Setup",
    },
    {
      id: "computer-combo",
      section: "computers",
      category: "Accessories",
      imageLabel: "Combo",
      title: "Wireless Keyboard and Mouse Combo",
      description: "Easy upsell product for laptop users and clean desk enthusiasts.",
      price: "NGN 21,500",
      affiliateUrl: "#replace-with-affiliate-link-computer-combo",
      badge: "Computer Accessory",
    },
    {
      id: "phone-infinix-hot",
      section: "budget",
      category: "Phones",
      imageLabel: "Phone",
      title: "Infinix Hot Series Smartphone",
      description: "Affordable Android option for social media, browsing, and small business use.",
      price: "NGN 145,000",
      affiliateUrl: "#replace-with-affiliate-link-phone-infinix-hot",
      badge: "Phone Pick",
    },
    {
      id: "phone-redmi-a",
      section: "value",
      category: "Phones",
      imageLabel: "Redmi",
      title: "Redmi A Series Smartphone",
      description: "Good value smartphone line for buyers who want battery life and everyday speed.",
      price: "NGN 128,000",
      affiliateUrl: "#replace-with-affiliate-link-phone-redmi-a",
      badge: "Best Value Phone",
    },
    {
      id: "phone-samsung-a",
      section: "trending",
      category: "Phones",
      imageLabel: "Galaxy",
      title: "Samsung Galaxy A Series",
      description: "Popular mid-range phone family with strong brand trust and camera appeal.",
      price: "NGN 265,000",
      affiliateUrl: "#replace-with-affiliate-link-phone-samsung-a",
      badge: "Trending Phone",
    },
    {
      id: "accessory-usb-drive",
      section: "budget",
      category: "Accessories",
      imageLabel: "USB",
      title: "64GB USB 3.0 Flash Drive",
      description: "Useful low-cost tech product for students, office workers, and everyday file transfer.",
      price: "NGN 11,500",
      affiliateUrl: "#replace-with-affiliate-link-usb-drive",
      badge: "Budget Accessory",
    },
    {
      id: "accessory-phone-stand",
      section: "value",
      category: "Accessories",
      imageLabel: "Stand",
      title: "Foldable Mobile Phone Stand",
      description: "A practical desk accessory for streaming, calls, and content creation.",
      price: "NGN 8,900",
      affiliateUrl: "#replace-with-affiliate-link-phone-stand",
      badge: "Best Value Deal",
    },
    {
      id: "laptop-hp-elitebook",
      section: "value",
      category: "Laptops",
      imageLabel: "HP",
      title: "HP EliteBook Refurbished Laptop",
      description: "A strong affiliate product for work buyers looking for reliability on a tighter budget.",
      price: "NGN 285,000",
      affiliateUrl: "#replace-with-affiliate-link-hp-elitebook",
      badge: "Laptop Deal",
    },
    {
      id: "laptop-lenovo-thinkpad",
      section: "trending",
      category: "Laptops",
      imageLabel: "Think",
      title: "Lenovo ThinkPad Refurbished",
      description: "Popular with business users, writers, and remote workers who want durability.",
      price: "NGN 310,000",
      affiliateUrl: "#replace-with-affiliate-link-lenovo-thinkpad",
      badge: "Trending Laptop",
    },
  ],
  shopFilters: [
    "All",
    "Budget Tech Picks",
    "Trending Gadgets",
    "Best Value Deals",
    "Phones",
    "Accessories",
    "Laptops",
  ],
  digitalTools: [
    {
      label: "AI Tool",
      title: "ChatGPT Plus",
      description: "Useful for writing, ideas, summaries, and faster business workflows.",
      affiliateUrl: "#replace-with-affiliate-link-chatgpt",
    },
    {
      label: "Design",
      title: "Canva Pro",
      description: "Great for social graphics, flyers, product posts, and brand assets.",
      affiliateUrl: "#replace-with-affiliate-link-canva",
    },
    {
      label: "Video",
      title: "CapCut Pro",
      description: "Fast editing for reels, ads, tutorials, and short-form product content.",
      affiliateUrl: "#replace-with-affiliate-link-capcut",
    },
    {
      label: "Productivity",
      title: "Notion",
      description: "Organize tasks, content calendars, research, and business systems in one place.",
      affiliateUrl: "#replace-with-affiliate-link-notion",
    },
    {
      label: "Downloads",
      title: "Kessy Labs Social Media Kit",
      description: "Placeholder downloadable resource you can later replace with your own template pack.",
      affiliateUrl: "#replace-with-affiliate-link-download-kit",
    },
    {
      label: "Commerce",
      title: "Paystack Storefront Tools",
      description: "Relevant local option for payment collection and simple Nigerian e-commerce flows.",
      affiliateUrl: "#replace-with-affiliate-link-paystack",
    },
  ],
  contentCards: [
    {
      label: "Video Review",
      title: "Best budget earbuds for under NGN 25,000",
      description: "A buyer-friendly video card format for affordable audio recommendations.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-earbuds",
    },
    {
      label: "Blog Style",
      title: "5 affordable gadgets students can actually use",
      description: "Great format for affiliate roundups, listicles, and search-friendly content.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-students",
    },
    {
      label: "Creator Guide",
      title: "Simple tech setup for new content creators",
      description: "Mix product cards with educational content that drives clicks naturally.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-creators",
    },
    {
      label: "Deal Alert",
      title: "Best value laptop accessories this month",
      description: "Reusable card style for recurring deal or roundup content.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-accessories",
    },
    {
      label: "Tool Breakdown",
      title: "Top digital tools for side hustles in Nigeria",
      description: "Supports affiliate links for software, apps, and downloads.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-tools",
    },
    {
      label: "Trending",
      title: "Products people keep asking about right now",
      description: "Good for homepage refreshes and fast-turnaround social content.",
      linkText: "Open feature",
      linkUrl: "#replace-with-content-link-trending",
    },
  ],
};
